CREATE TABLE USERS(
   ID   INT              NOT NULL AUTO_INCREMENT,
   UUID VARCHAR (255)    NOT NULL UNIQUE,
   FirstName VARCHAR (255)    NOT NULL,
   LastName VARCHAR (255)    NOT NULL,
   Country VARCHAR (255)    ,
   Email VARCHAR (255)    NOT NULL UNIQUE,
   Login VARCHAR (255)    NOT NULL UNIQUE,
   Password VARCHAR (255)    NOT NULL,
   PhoneNumber VARCHAR (255)    NOT NULL,
   Birthday TIMESTAMP NOT NULL,-- DEFAULT CURRENT_DATE(),

   PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX EMAIL_USERS ON USERS (EMAIL);
CREATE UNIQUE INDEX LOGIN_USERS ON USERS (LOGIN);
CREATE UNIQUE INDEX UUID_USERS ON USERS (UUID);